"""changes

Revision ID: 043b142a3fa2
Revises: ae1eb1ba12c7
Create Date: 2021-11-10 19:30:28.811314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '043b142a3fa2'
down_revision = 'ae1eb1ba12c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'admin_pass_wd',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_foreign_key(None, 'admins', 'users', ['admin_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.alter_column('admins', 'admin_pass_wd',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
