"""delete column fone_mic

Revision ID: 0f8bba5e35ab
Revises: 631aaeb7f853
Create Date: 2021-12-15 14:05:52.327602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f8bba5e35ab'
down_revision = '631aaeb7f853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fones_ibfk_2', 'fones', type_='foreignkey')
    op.drop_column('fones', 'fone_mic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fones', sa.Column('fone_mic', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fones_ibfk_2', 'fones', 'mics', ['fone_mic'], ['mic_id'])
    # ### end Alembic commands ###
