"""change unique patrimony

Revision ID: 1e687648d0e3
Revises: 94a095f1ab26
Create Date: 2021-12-15 16:06:20.843969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e687648d0e3'
down_revision = '94a095f1ab26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('patrimony', table_name='equipments')
    op.drop_index('patrimony_2', table_name='equipments')
    op.create_unique_constraint(None, 'equipments', ['patrimony', 'equip_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipments', type_='unique')
    op.create_index('patrimony_2', 'equipments', ['patrimony'], unique=False)
    op.create_index('patrimony', 'equipments', ['patrimony', 'equip_user_id', 'equip_id'], unique=False)
    # ### end Alembic commands ###
