"""empty message

Revision ID: 4b2b7ee66927
Revises: f137d3248a76
Create Date: 2021-11-09 17:06:10.859714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2b7ee66927'
down_revision = 'f137d3248a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=64), nullable=True),
    sa.Column('admin_pass_wd', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_admin_name'), 'admins', ['admin_name'], unique=True)
    op.create_table('connections',
    sa.Column('connection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=False),
    sa.Column('team_leader', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('subteams',
    sa.Column('subteam_team_id', sa.Integer(), nullable=True),
    sa.Column('subteam_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subtime_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['subteam_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('subteam_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_register', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('user_team_id', sa.Integer(), nullable=False),
    sa.Column('user_subteam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_subteam_id'], ['subteams.subteam_id'], ),
    sa.ForeignKeyConstraint(['user_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_register', 'user_name')
    )
    op.create_table('equipments',
    sa.Column('equip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equip_user_id', sa.Integer(), nullable=False),
    sa.Column('patrimony', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('registry', sa.String(length=64), nullable=True),
    sa.Column('general_description', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['equip_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('equip_id'),
    sa.UniqueConstraint('patrimony', 'equip_user_id')
    )
    op.create_table('calls',
    sa.Column('call_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_equipment_id', sa.Integer(), nullable=False),
    sa.Column('call_open', sa.String(length=64), nullable=True),
    sa.Column('call_close', sa.String(length=64), nullable=True),
    sa.Column('call_solution', sa.String(length=700), nullable=True),
    sa.ForeignKeyConstraint(['call_equipment_id'], ['equipments.equip_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_table('computers',
    sa.Column('computer_id', sa.Integer(), nullable=False),
    sa.Column('computer_cpu', sa.String(length=64), nullable=True),
    sa.Column('computer_memory', sa.String(length=64), nullable=True),
    sa.Column('computer_hd', sa.String(length=64), nullable=True),
    sa.Column('computer_vga', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['computer_id'], ['equipments.equip_id'], ),
    sa.PrimaryKeyConstraint('computer_id')
    )
    op.create_table('equipment_connetions',
    sa.Column('equipment', sa.Integer(), nullable=False),
    sa.Column('connection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection'], ['connections.connection_id'], ),
    sa.ForeignKeyConstraint(['equipment'], ['equipments.equip_id'], ),
    sa.PrimaryKeyConstraint('equipment', 'connection')
    )
    op.create_table('mics',
    sa.Column('mic_id', sa.Integer(), nullable=False),
    sa.Column('mic_noise_cancellation', sa.String(length=64), nullable=True),
    sa.Column('mic_frequency', sa.String(length=64), nullable=True),
    sa.Column('mic_impedance', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mic_id'], ['equipments.equip_id'], ),
    sa.PrimaryKeyConstraint('mic_id')
    )
    op.create_table('monitors',
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('monitor_size', sa.String(length=64), nullable=True),
    sa.Column('monitor_resolution', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['equipments.equip_id'], ),
    sa.PrimaryKeyConstraint('monitor_id')
    )
    op.create_table('webcams',
    sa.Column('webcam_id', sa.Integer(), nullable=False),
    sa.Column('webcam_resolution', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['webcam_id'], ['equipments.equip_id'], ),
    sa.PrimaryKeyConstraint('webcam_id')
    )
    op.create_table('fones',
    sa.Column('fone_id', sa.Integer(), nullable=False),
    sa.Column('fone_frequency', sa.String(length=64), nullable=True),
    sa.Column('fone_impedance', sa.String(length=64), nullable=True),
    sa.Column('fone_driver', sa.String(length=64), nullable=True),
    sa.Column('fone_noise_cancellation', sa.String(length=64), nullable=True),
    sa.Column('fone_mic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fone_id'], ['equipments.equip_id'], ),
    sa.ForeignKeyConstraint(['fone_mic'], ['mics.mic_id'], ),
    sa.PrimaryKeyConstraint('fone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fones')
    op.drop_table('webcams')
    op.drop_table('monitors')
    op.drop_table('mics')
    op.drop_table('equipment_connetions')
    op.drop_table('computers')
    op.drop_table('calls')
    op.drop_table('equipments')
    op.drop_table('users')
    op.drop_table('subteams')
    op.drop_table('teams')
    op.drop_table('connections')
    op.drop_index(op.f('ix_admins_admin_name'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
