"""table args just patrimony

Revision ID: 5d8c10872039
Revises: 1e687648d0e3
Create Date: 2021-12-15 16:49:43.393352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8c10872039'
down_revision = '1e687648d0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('patrimony', table_name='equipments')
    op.create_unique_constraint(None, 'equipments', ['patrimony'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipments', type_='unique')
    op.create_index('patrimony', 'equipments', ['patrimony', 'equip_user_id'], unique=False)
    # ### end Alembic commands ###
