"""biginte patrimony

Revision ID: 631aaeb7f853
Revises: e45067f6b920
Create Date: 2021-12-15 13:49:03.069867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631aaeb7f853'
down_revision = 'e45067f6b920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('computers_ibfk_1', 'computers', type_='foreignkey')
    op.create_foreign_key(None, 'computers', 'equipments', ['computer_id'], ['equip_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'computers', type_='foreignkey')
    op.create_foreign_key('computers_ibfk_1', 'computers', 'equipments', ['computer_id'], ['equip_id'])
    # ### end Alembic commands ###
