"""empty message

Revision ID: b524b2b3a06c
Revises: d98c9e7255f9
Create Date: 2023-01-05 17:45:36.993958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b524b2b3a06c'
down_revision = 'd98c9e7255f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'admin_pass_wd')
    op.add_column('users', sa.Column('user_pass', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_pass')
    op.add_column('admins', sa.Column('admin_pass_wd', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False))
    # ### end Alembic commands ###
