"""empty message

Revision ID: d98c9e7255f9
Revises: 5d8c10872039
Create Date: 2023-01-03 15:46:47.856625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd98c9e7255f9'
down_revision = '5d8c10872039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('call_technican', sa.Integer(), nullable=False))
    op.alter_column('calls', 'call_open',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               nullable=False)
    op.create_foreign_key(None, 'calls', 'users', ['call_technican'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.alter_column('calls', 'call_open',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               nullable=True)
    op.drop_column('calls', 'call_technican')
    # ### end Alembic commands ###
