"""add patrimony unique

Revision ID: e45067f6b920
Revises: 5e5a732bd940
Create Date: 2021-12-10 10:10:24.054375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45067f6b920'
down_revision = '5e5a732bd940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'equipments', ['patrimony'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipments', type_='unique')
    # ### end Alembic commands ###
